/*
 * generated by Xtext 2.43.0
 */
package org.emoflon.gips.gipsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.emoflon.gips.gipsl.gipsl.EditorGTFile
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
 
@ExtendWith(InjectionExtension)
@InjectWith(GipslInjectorProvider)
class GipslParsingTest {
	@Inject
	ParseHelper<EditorGTFile> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			package "gipsl.solverconfig.withoutsolverargs"
			import "http://www.eclipse.org/emf/2002/Ecore"
			
			config {
				solver := GUROBI;
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
